model: /path/tollama-7b
epochs: 20
output_dir: OmniQuant/log/llama-7b

wbits: 3
abits: 16

lwc: true        
eval_ppl: true    

nsamples: 128
ckpt: /path/to/OmniQuant/test.pt

cuda_visible_devices: "1"
